#!/bin/sh
set -e

case "$1" in
  install)
    # If we are doing a fresh install, then these files are no longer needed.
    # They were around for a very short time and are best simply removed.
    rm -f /etc/logrotate.d/openresty
    ;;

  upgrade)
    # If this is an upgrade, then they might have the UFW profile in the wrong spot.
    if [ -d /etc/ufw/applications.d/openresty ]; then
      rm -f /etc/ufw/applications.d/openresty/ufw.profile
      rmdir /etc/ufw/applications.d/openresty
    fi
    rm -f /etc/logrotate.d/openresty
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
